"""Render ``tests/mutation-report.md`` from mutmut results + the JSON exemption log.

The markdown report used to be hand-maintained (commit 1ae4902 fixed a
hand-counted drift). Plan 2.1 replaces the hand-counting with this
generator: it reads ``mutmut results`` output, cross-references the
exemption JSON, and renders the same shape that the v1.1.0 report
carried.

Usage (from the repo root)::

    UV_CACHE_DIR=$PWD/.cache/uv uv run mutmut run
    UV_CACHE_DIR=$PWD/.cache/uv uv run python scripts/gen_mutation_report.py

The generator is idempotent: re-running it after a fresh ``mutmut run``
overwrites the file in place. The header line states the script + the
mutmut version so reviewers know the count is machine-rendered, not
hand-edited.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EXEMPTIONS_PATH = REPO_ROOT / "tests" / "mutation-exemptions.json"
REPORT_PATH = REPO_ROOT / "tests" / "mutation-report.md"
MUTMUT_BIN = "mutmut"


def _run_mutmut_results() -> str:
    """Invoke ``mutmut results`` and return stdout text.

    mutmut prints a textual table (one row per mutant id). Tests live
    under ``tests/`` so the test runner mutmut invokes stays the same as
    the one in pyproject.toml (``[tool.mutmut] source_paths``).
    """
    proc = subprocess.run(
        [MUTMUT_BIN, "results"],
        cwd=str(REPO_ROOT),
        check=False,
        capture_output=True,
        text=True,
    )
    if proc.returncode not in (0, 1):
        # mutmut returns 1 when survivors exist; that's the normal case we
        # want to render. Only fail hard on a non-zero non-1 return.
        sys.stderr.write(f"mutmut results exited {proc.returncode}:\n{proc.stderr}\n")
        sys.exit(proc.returncode)
    return proc.stdout


_STATUS_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    # Order matters: more-specific first. mutmut prefixes the id with a
    # status emoji; we strip the emoji and keep the id + status label.
    ("Killed", re.compile(r"^\s*\U0001f389\s+(\S+)\s+Killed\s*$")),
    ("Survived", re.compile(r"^\s*\U0001f616\s+(\S+)\s+Survived\s*$")),
    ("NoTests", re.compile(r"^\s*\U0001fae5\s+(\S+)\s+no.*tests.*$", re.IGNORECASE)),
    ("Timeout", re.compile(r"^\s*\u23f0\s+(\S+)\s+Timeout\s*$")),
)


def _parse_results(text: str) -> Counter[str]:
    """Return ``Counter`` mapping status label → count of mutants."""
    counts: Counter[str] = Counter()
    for line in text.splitlines():
        for label, pattern in _STATUS_PATTERNS:
            if pattern.match(line):
                counts[label] += 1
                break
    return counts


def _load_exemptions() -> list[dict[str, str]]:
    """Read the JSON exemption log (structure: ``[{category, pattern, reason}, ...]``)."""
    if not EXEMPTIONS_PATH.exists():
        return []
    with EXEMPTIONS_PATH.open(encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, list):
        raise ValueError(f"{EXEMPTIONS_PATH} must be a JSON list; got {type(data).__name__}")
    return data


def _detect_mutmut_version() -> str:
    """Return ``mutmut --version`` output (e.g. ``mutmut, version 3.7.0``)."""
    proc = subprocess.run(
        [MUTMUT_BIN, "--version"],
        cwd=str(REPO_ROOT),
        check=False,
        capture_output=True,
        text=True,
    )
    return proc.stdout.strip() or "mutmut (version unknown)"


def _render(counts: Counter[str], exemptions: list[dict[str, str]], version: str) -> str:
    """Render the markdown body for ``tests/mutation-report.md``."""
    killed = counts.get("Killed", 0)
    survived = counts.get("Survived", 0)
    no_tests = counts.get("NoTests", 0)
    timeout = counts.get("Timeout", 0)
    total = killed + survived + no_tests + timeout

    exempt_total = sum(int(e.get("count", 0)) for e in exemptions)

    lines: list[str] = []
    lines.append("# Mutation Triage Report")
    lines.append("")
    lines.append(
        "> Generated by `scripts/gen_mutation_report.py` (plan 2.1). "
        f"Tool: `{version}` against `src/sunxue_gates` (tables.py is "
        "excluded via `[tool.mutmut] do_not_mutate`). "
        "Do not hand-edit the count rows below — re-run the generator."
    )
    lines.append("")
    lines.append("Final tally (machine-rendered):")
    lines.append("")
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Killed by tests | {killed} |")
    lines.append(f"| No tests collected | {no_tests} |")
    lines.append(f"| Survived | {survived} |")
    lines.append(f"| Timeout | {timeout} |")
    lines.append("")
    if total:
        ratio = survived / total * 100
        lines.append(f"Survivor rate: **{ratio:.1f}%** ({survived}/{total})")
        lines.append("")
    if exempt_total:
        lines.append(
            f"Categorised exemption total: **{exempt_total}** "
            f"(spread across {len(exemptions)} entries — see `tests/mutation-exemptions.json`)."
        )
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Exemption categories")
    lines.append("")
    if not exemptions:
        lines.append(
            "_No exemption entries yet. tester-2 will populate "
            "`tests/mutation-exemptions.json` during W3 per the parent brief._"
        )
        lines.append("")
    else:
        lines.append("| Category | Pattern | Mutants | Reason |")
        lines.append("|----------|---------|---------|--------|")
        for e in exemptions:
            lines.append(
                f"| {e.get('category', '?')} "
                f"| `{e.get('pattern', '?')}` "
                f"| {e.get('count', 0)} "
                f"| {e.get('reason', '?')} |"
            )
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Methodology notes")
    lines.append("")
    lines.append(
        "- This report is rendered by `scripts/gen_mutation_report.py`. "
        "Re-run after any `mutmut run` to refresh counts."
    )
    lines.append(
        "- `tests/mutation-exemptions.json` is the single source of truth for "
        "categorised survivors; the script reads it as `[category, pattern, "
        "reason, count]` entries."
    )
    lines.append(
        "- `tests/unit/test_golden_literals.py` pins the keyword/pattern "
        "tables in `src/sunxue_gates/tables.py` via SHA-256 + UTF-8 hex "
        "against `tests/golden/literals.json`; the table-quality signal "
        "moves from mutmut to the golden contract."
    )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Don't write; just print the rendered body to stdout.",
    )
    args = parser.parse_args(argv)

    raw = _run_mutmut_results()
    counts = _parse_results(raw)
    exemptions = _load_exemptions()
    version = _detect_mutmut_version()
    body = _render(counts, exemptions, version)

    if args.check:
        sys.stdout.write(body)
        return 0

    REPORT_PATH.write_text(body, encoding="utf-8")
    print(f"Wrote {REPORT_PATH}")
    print(f"  killed={counts.get('Killed', 0)}")
    print(f"  survived={counts.get('Survived', 0)}")
    print(f"  no_tests={counts.get('NoTests', 0)}")
    print(f"  timeout={counts.get('Timeout', 0)}")
    print(f"  exemptions listed={len(exemptions)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
